import 'dotenv/config';
import { masterDb } from '../db';
import { countries } from '../db/master/schema';

async function seedCountries() {
  console.log('🌱 Iniciando seed de países...');

  const countriesData = [
    { name: 'Afganistán', isoCode: 'AFG', dialCode: '+93', isActive: false },
    { name: 'Albania', isoCode: 'ALB', dialCode: '+355', isActive: true },
    { name: 'Alemania', isoCode: 'DEU', dialCode: '+49', isActive: true },
    { name: 'Andorra', isoCode: 'AND', dialCode: '+376', isActive: true },
    { name: 'Angola', isoCode: 'AGO', dialCode: '+244', isActive: false },
    { name: 'Anguila', isoCode: 'AIA', dialCode: '+1-264', isActive: true },
    { name: 'Antártida', isoCode: 'ATA', dialCode: '+672', isActive: false },
    { name: 'Antigua y Barbuda', isoCode: 'ATG', dialCode: '+1-268', isActive: true },
    { name: 'Arabia Saudita', isoCode: 'SAU', dialCode: '+966', isActive: false },
    { name: 'Argelia', isoCode: 'DZA', dialCode: '+213', isActive: false },
    { name: 'Argentina', isoCode: 'ARG', dialCode: '+54', isActive: true },
    { name: 'Armenia', isoCode: 'ARM', dialCode: '+374', isActive: false },
    { name: 'Aruba', isoCode: 'ABW', dialCode: '+297', isActive: true },
    { name: 'Australia', isoCode: 'AUS', dialCode: '+61', isActive: false },
    { name: 'Austria', isoCode: 'AUT', dialCode: '+43', isActive: true },
    { name: 'Azerbaiyán', isoCode: 'AZE', dialCode: '+994', isActive: false },
    { name: 'Bahamas', isoCode: 'BHS', dialCode: '+1-242', isActive: true },
    { name: 'Bangladés', isoCode: 'BGD', dialCode: '+880', isActive: false },
    { name: 'Barbados', isoCode: 'BRB', dialCode: '+1-246', isActive: true },
    { name: 'Baréin', isoCode: 'BHR', dialCode: '+973', isActive: false },
    { name: 'Bélgica', isoCode: 'BEL', dialCode: '+32', isActive: true },
    { name: 'Belice', isoCode: 'BLZ', dialCode: '+501', isActive: true },
    { name: 'Benín', isoCode: 'BEN', dialCode: '+229', isActive: false },
    { name: 'Bermudas', isoCode: 'BMU', dialCode: '+1-441', isActive: true },
    { name: 'Bielorrusia', isoCode: 'BLR', dialCode: '+375', isActive: true },
    { name: 'Bolivia', isoCode: 'BOL', dialCode: '+591', isActive: true },
    { name: 'Bonaire, San Eustaquio y Saba', isoCode: 'BES', dialCode: '+599', isActive: true },
    { name: 'Bosnia y Herzegovina', isoCode: 'BIH', dialCode: '+387', isActive: true },
    { name: 'Botsuana', isoCode: 'BWA', dialCode: '+267', isActive: false },
    { name: 'Brasil', isoCode: 'BRA', dialCode: '+55', isActive: true },
    { name: 'Brunéi', isoCode: 'BRN', dialCode: '+673', isActive: false },
    { name: 'Bulgaria', isoCode: 'BGR', dialCode: '+359', isActive: true },
    { name: 'Burkina Faso', isoCode: 'BFA', dialCode: '+226', isActive: false },
    { name: 'Burundi', isoCode: 'BDI', dialCode: '+257', isActive: false },
    { name: 'Bután', isoCode: 'BTN', dialCode: '+975', isActive: false },
    { name: 'Cabo Verde', isoCode: 'CPV', dialCode: '+238', isActive: false },
    { name: 'Camboya', isoCode: 'KHM', dialCode: '+855', isActive: false },
    { name: 'Camerún', isoCode: 'CMR', dialCode: '+237', isActive: false },
    { name: 'Canadá', isoCode: 'CAN', dialCode: '+1', isActive: true },
    { name: 'Catar', isoCode: 'QAT', dialCode: '+974', isActive: false },
    { name: 'Chad', isoCode: 'TCD', dialCode: '+235', isActive: false },
    { name: 'Chile', isoCode: 'CHL', dialCode: '+56', isActive: true },
    { name: 'China', isoCode: 'CHN', dialCode: '+86', isActive: false },
    { name: 'Chipre', isoCode: 'CYP', dialCode: '+357', isActive: true },
    { name: 'Colombia', isoCode: 'COL', dialCode: '+57', isActive: true },
    { name: 'Comoras', isoCode: 'COM', dialCode: '+269', isActive: false },
    { name: 'Corea del Norte', isoCode: 'PRK', dialCode: '+850', isActive: false },
    { name: 'Corea del Sur', isoCode: 'KOR', dialCode: '+82', isActive: false },
    { name: 'Costa de Marfil', isoCode: 'CIV', dialCode: '+225', isActive: false },
    { name: 'Costa Rica', isoCode: 'CRI', dialCode: '+506', isActive: true },
    { name: 'Croacia', isoCode: 'HRV', dialCode: '+385', isActive: true },
    { name: 'Cuba', isoCode: 'CUB', dialCode: '+53', isActive: true },
    { name: 'Curazao', isoCode: 'CUW', dialCode: '+599', isActive: true },
    { name: 'Dinamarca', isoCode: 'DNK', dialCode: '+45', isActive: true },
    { name: 'Dominica', isoCode: 'DMA', dialCode: '+1-767', isActive: true },
    { name: 'Ecuador', isoCode: 'ECU', dialCode: '+593', isActive: true },
    { name: 'Egipto', isoCode: 'EGY', dialCode: '+20', isActive: false },
    { name: 'El Salvador', isoCode: 'SLV', dialCode: '+503', isActive: true },
    { name: 'Emiratos Árabes Unidos', isoCode: 'ARE', dialCode: '+971', isActive: false },
    { name: 'Eritrea', isoCode: 'ERI', dialCode: '+291', isActive: false },
    { name: 'Eslovaquia', isoCode: 'SVK', dialCode: '+421', isActive: true },
    { name: 'Eslovenia', isoCode: 'SVN', dialCode: '+386', isActive: true },
    { name: 'España', isoCode: 'ESP', dialCode: '+34', isActive: true },
    { name: 'Estados Unidos', isoCode: 'USA', dialCode: '+1', isActive: true },
    { name: 'Eswatini', isoCode: 'SWZ', dialCode: '+268', isActive: false },
    { name: 'Estonia', isoCode: 'EST', dialCode: '+372', isActive: true },
    { name: 'Etiopía', isoCode: 'ETH', dialCode: '+251', isActive: false },
    { name: 'Filipinas', isoCode: 'PHL', dialCode: '+63', isActive: false },
    { name: 'Finlandia', isoCode: 'FIN', dialCode: '+358', isActive: true },
    { name: 'Fiyi', isoCode: 'FJI', dialCode: '+679', isActive: false },
    { name: 'Francia', isoCode: 'FRA', dialCode: '+33', isActive: true },
    { name: 'Gabón', isoCode: 'GAB', dialCode: '+241', isActive: false },
    { name: 'Gambia', isoCode: 'GMB', dialCode: '+220', isActive: false },
    { name: 'Georgia', isoCode: 'GEO', dialCode: '+995', isActive: false },
    { name: 'Georgia del Sur y las Islas Sandwich del Sur', isoCode: 'SGS', dialCode: '+500', isActive: false },
    { name: 'Ghana', isoCode: 'GHA', dialCode: '+233', isActive: false },
    { name: 'Gibraltar', isoCode: 'GIB', dialCode: '+350', isActive: true },
    { name: 'Granada', isoCode: 'GRD', dialCode: '+1-473', isActive: true },
    { name: 'Guernsey', isoCode: 'GGY', dialCode: '+44', isActive: true },
    { name: 'Grecia', isoCode: 'GRC', dialCode: '+30', isActive: true },
    { name: 'Groenlandia', isoCode: 'GRL', dialCode: '+299', isActive: true },
    { name: 'Guadalupe', isoCode: 'GLP', dialCode: '+590', isActive: true },
    { name: 'Guam', isoCode: 'GUM', dialCode: '+1-671', isActive: false },
    { name: 'Guatemala', isoCode: 'GTM', dialCode: '+502', isActive: true },
    { name: 'Guayana Francesa', isoCode: 'GUF', dialCode: '+594', isActive: true },
    { name: 'Guinea', isoCode: 'GIN', dialCode: '+224', isActive: false },
    { name: 'Guinea Ecuatorial', isoCode: 'GNQ', dialCode: '+240', isActive: false },
    { name: 'Guinea-Bisáu', isoCode: 'GNB', dialCode: '+245', isActive: false },
    { name: 'Guyana', isoCode: 'GUY', dialCode: '+592', isActive: true },
    { name: 'Haití', isoCode: 'HTI', dialCode: '+509', isActive: true },
    { name: 'Honduras', isoCode: 'HND', dialCode: '+504', isActive: true },
    { name: 'Hong Kong', isoCode: 'HKG', dialCode: '+852', isActive: false },
    { name: 'Hungría', isoCode: 'HUN', dialCode: '+36', isActive: true },
    { name: 'India', isoCode: 'IND', dialCode: '+91', isActive: false },
    { name: 'Indonesia', isoCode: 'IDN', dialCode: '+62', isActive: false },
    { name: 'Irak', isoCode: 'IRQ', dialCode: '+964', isActive: false },
    { name: 'Irán', isoCode: 'IRN', dialCode: '+98', isActive: false },
    { name: 'Irlanda', isoCode: 'IRL', dialCode: '+353', isActive: true },
    { name: 'Isla Bouvet', isoCode: 'BVT', dialCode: '+47', isActive: false },
    { name: 'Isla de Man', isoCode: 'IMN', dialCode: '+44', isActive: true },
    { name: 'Isla de Navidad', isoCode: 'CXR', dialCode: '+61', isActive: false },
    { name: 'Isla Norfolk', isoCode: 'NFK', dialCode: '+672', isActive: false },
    { name: 'Islandia', isoCode: 'ISL', dialCode: '+354', isActive: true },
    { name: 'Islas Åland', isoCode: 'ALA', dialCode: '+358', isActive: true },
    { name: 'Islas Caimán', isoCode: 'CYM', dialCode: '+1-345', isActive: true },
    { name: 'Islas Cocos (Keeling)', isoCode: 'CCK', dialCode: '+61', isActive: false },
    { name: 'Islas Cook', isoCode: 'COK', dialCode: '+682', isActive: false },
    { name: 'Islas Feroe', isoCode: 'FRO', dialCode: '+298', isActive: true },
    { name: 'Islas Heard y McDonald', isoCode: 'HMD', dialCode: '+672', isActive: false },
    { name: 'Islas Malvinas', isoCode: 'FLK', dialCode: '+500', isActive: true },
    { name: 'Islas Marianas del Norte', isoCode: 'MNP', dialCode: '+1-670', isActive: false },
    { name: 'Islas Marshall', isoCode: 'MHL', dialCode: '+692', isActive: false },
    { name: 'Islas Salomón', isoCode: 'SLB', dialCode: '+677', isActive: false },
    { name: 'Islas Turcas y Caicos', isoCode: 'TCA', dialCode: '+1-649', isActive: true },
    { name: 'Islas Ultramarinas Menores de los EE. UU.', isoCode: 'UMI', dialCode: '+1', isActive: false },
    { name: 'Islas Vírgenes Británicas', isoCode: 'VGB', dialCode: '+1-284', isActive: true },
    { name: 'Islas Vírgenes de los EE. UU.', isoCode: 'VIR', dialCode: '+1-340', isActive: true },
    { name: 'Israel', isoCode: 'ISR', dialCode: '+972', isActive: false },
    { name: 'Italia', isoCode: 'ITA', dialCode: '+39', isActive: true },
    { name: 'Jamaica', isoCode: 'JAM', dialCode: '+1-876', isActive: true },
    { name: 'Japón', isoCode: 'JPN', dialCode: '+81', isActive: false },
    { name: 'Jersey', isoCode: 'JEY', dialCode: '+44', isActive: true },
    { name: 'Jordania', isoCode: 'JOR', dialCode: '+962', isActive: false },
    { name: 'Kazajistán', isoCode: 'KAZ', dialCode: '+7', isActive: false },
    { name: 'Kenia', isoCode: 'KEN', dialCode: '+254', isActive: false },
    { name: 'Kirguistán', isoCode: 'KGZ', dialCode: '+996', isActive: false },
    { name: 'Kiribati', isoCode: 'KIR', dialCode: '+686', isActive: false },
    { name: 'Kosovo', isoCode: 'XKX', dialCode: '+383', isActive: true },
    { name: 'Kuwait', isoCode: 'KWT', dialCode: '+965', isActive: false },
    { name: 'Laos', isoCode: 'LAO', dialCode: '+856', isActive: false },
    { name: 'Lesoto', isoCode: 'LSO', dialCode: '+266', isActive: false },
    { name: 'Letonia', isoCode: 'LVA', dialCode: '+371', isActive: true },
    { name: 'Líbano', isoCode: 'LBN', dialCode: '+961', isActive: false },
    { name: 'Liberia', isoCode: 'LBR', dialCode: '+231', isActive: false },
    { name: 'Libia', isoCode: 'LBY', dialCode: '+218', isActive: false },
    { name: 'Liechtenstein', isoCode: 'LIE', dialCode: '+423', isActive: true },
    { name: 'Lituania', isoCode: 'LTU', dialCode: '+370', isActive: true },
    { name: 'Luxemburgo', isoCode: 'LUX', dialCode: '+352', isActive: true },
    { name: 'Macao', isoCode: 'MAC', dialCode: '+853', isActive: false },
    { name: 'Macedonia del Norte', isoCode: 'MKD', dialCode: '+389', isActive: true },
    { name: 'Madagascar', isoCode: 'MDG', dialCode: '+261', isActive: false },
    { name: 'Malasia', isoCode: 'MYS', dialCode: '+60', isActive: false },
    { name: 'Malaui', isoCode: 'MWI', dialCode: '+265', isActive: false },
    { name: 'Maldivas', isoCode: 'MDV', dialCode: '+960', isActive: false },
    { name: 'Malí', isoCode: 'MLI', dialCode: '+223', isActive: false },
    { name: 'Malta', isoCode: 'MLT', dialCode: '+356', isActive: true },
    { name: 'Marruecos', isoCode: 'MAR', dialCode: '+212', isActive: false },
    { name: 'Martinica', isoCode: 'MTQ', dialCode: '+596', isActive: true },
    { name: 'Mauricio', isoCode: 'MUS', dialCode: '+230', isActive: false },
    { name: 'Mauritania', isoCode: 'MRT', dialCode: '+222', isActive: false },
    { name: 'Mayotte', isoCode: 'MYT', dialCode: '+262', isActive: false },
    { name: 'México', isoCode: 'MEX', dialCode: '+52', isActive: true },
    { name: 'Micronesia', isoCode: 'FSM', dialCode: '+691', isActive: false },
    { name: 'Moldavia', isoCode: 'MDA', dialCode: '+373', isActive: true },
    { name: 'Mónaco', isoCode: 'MCO', dialCode: '+377', isActive: true },
    { name: 'Mongolia', isoCode: 'MNG', dialCode: '+976', isActive: false },
    { name: 'Montenegro', isoCode: 'MNE', dialCode: '+382', isActive: true },
    { name: 'Montserrat', isoCode: 'MSR', dialCode: '+1-664', isActive: true },
    { name: 'Mozambique', isoCode: 'MOZ', dialCode: '+258', isActive: false },
    { name: 'Myanmar', isoCode: 'MMR', dialCode: '+95', isActive: false },
    { name: 'Namibia', isoCode: 'NAM', dialCode: '+264', isActive: false },
    { name: 'Nauru', isoCode: 'NRU', dialCode: '+674', isActive: false },
    { name: 'Nepal', isoCode: 'NPL', dialCode: '+977', isActive: false },
    { name: 'Nicaragua', isoCode: 'NIC', dialCode: '+505', isActive: true },
    { name: 'Níger', isoCode: 'NER', dialCode: '+227', isActive: false },
    { name: 'Nigeria', isoCode: 'NGA', dialCode: '+234', isActive: false },
    { name: 'Niue', isoCode: 'NIU', dialCode: '+683', isActive: false },
    { name: 'Noruega', isoCode: 'NOR', dialCode: '+47', isActive: true },
    { name: 'Nueva Caledonia', isoCode: 'NCL', dialCode: '+687', isActive: false },
    { name: 'Nueva Zelanda', isoCode: 'NZL', dialCode: '+64', isActive: false },
    { name: 'Omán', isoCode: 'OMN', dialCode: '+968', isActive: false },
    { name: 'Países Bajos', isoCode: 'NLD', dialCode: '+31', isActive: true },
    { name: 'Pakistán', isoCode: 'PAK', dialCode: '+92', isActive: false },
    { name: 'Palaos', isoCode: 'PLW', dialCode: '+680', isActive: false },
    { name: 'Palestina', isoCode: 'PSE', dialCode: '+970', isActive: false },
    { name: 'Panamá', isoCode: 'PAN', dialCode: '+507', isActive: true },
    { name: 'Papúa Nueva Guinea', isoCode: 'PNG', dialCode: '+675', isActive: false },
    { name: 'Paraguay', isoCode: 'PRY', dialCode: '+595', isActive: true },
    { name: 'Perú', isoCode: 'PER', dialCode: '+51', isActive: true },
    { name: 'Pitcairn', isoCode: 'PCN', dialCode: '+64', isActive: false },
    { name: 'Polinesia Francesa', isoCode: 'PYF', dialCode: '+689', isActive: false },
    { name: 'Polonia', isoCode: 'POL', dialCode: '+48', isActive: true },
    { name: 'Portugal', isoCode: 'PRT', dialCode: '+351', isActive: true },
    { name: 'Puerto Rico', isoCode: 'PRI', dialCode: '+1-787', isActive: true },
    { name: 'Reino Unido', isoCode: 'GBR', dialCode: '+44', isActive: true },
    { name: 'República Centroafricana', isoCode: 'CAF', dialCode: '+236', isActive: false },
    { name: 'República Checa', isoCode: 'CZE', dialCode: '+420', isActive: true },
    { name: 'República del Congo', isoCode: 'COG', dialCode: '+242', isActive: false },
    { name: 'República Democrática del Congo', isoCode: 'COD', dialCode: '+243', isActive: false },
    { name: 'República Dominicana', isoCode: 'DOM', dialCode: '+1-809', isActive: true },
    { name: 'Reunión', isoCode: 'REU', dialCode: '+262', isActive: false },
    { name: 'Ruanda', isoCode: 'RWA', dialCode: '+250', isActive: false },
    { name: 'Rumania', isoCode: 'ROU', dialCode: '+40', isActive: true },
    { name: 'Rusia', isoCode: 'RUS', dialCode: '+7', isActive: true },
    { name: 'Sáhara Occidental', isoCode: 'ESH', dialCode: '+212', isActive: false },
    { name: 'Samoa', isoCode: 'WSM', dialCode: '+685', isActive: false },
    { name: 'Samoa Americana', isoCode: 'ASM', dialCode: '+1-684', isActive: false },
    { name: 'San Bartolomé', isoCode: 'BLM', dialCode: '+590', isActive: true },
    { name: 'San Cristóbal y Nieves', isoCode: 'KNA', dialCode: '+1-869', isActive: true },
    { name: 'San Marino', isoCode: 'SMR', dialCode: '+378', isActive: true },
    { name: 'San Martín', isoCode: 'MAF', dialCode: '+590', isActive: true },
    { name: 'San Pedro y Miquelón', isoCode: 'SPM', dialCode: '+508', isActive: true },
    { name: 'San Vicente y las Granadinas', isoCode: 'VCT', dialCode: '+1-784', isActive: true },
    { name: 'Santa Elena, Ascensión y Tristán de Acuña', isoCode: 'SHN', dialCode: '+290', isActive: false },
    { name: 'Santa Lucía', isoCode: 'LCA', dialCode: '+1-758', isActive: true },
    { name: 'Santo Tomé y Príncipe', isoCode: 'STP', dialCode: '+239', isActive: false },
    { name: 'Senegal', isoCode: 'SEN', dialCode: '+221', isActive: false },
    { name: 'Serbia', isoCode: 'SRB', dialCode: '+381', isActive: true },
    { name: 'Seychelles', isoCode: 'SYC', dialCode: '+248', isActive: false },
    { name: 'Sierra Leona', isoCode: 'SLE', dialCode: '+232', isActive: false },
    { name: 'Singapur', isoCode: 'SGP', dialCode: '+65', isActive: false },
    { name: 'Sint Maarten', isoCode: 'SXM', dialCode: '+1-721', isActive: true },
    { name: 'Siria', isoCode: 'SYR', dialCode: '+963', isActive: false },
    { name: 'Somalia', isoCode: 'SOM', dialCode: '+252', isActive: false },
    { name: 'Sri Lanka', isoCode: 'LKA', dialCode: '+94', isActive: false },
    { name: 'Sudáfrica', isoCode: 'ZAF', dialCode: '+27', isActive: false },
    { name: 'Sudán', isoCode: 'SDN', dialCode: '+249', isActive: false },
    { name: 'Sudán del Sur', isoCode: 'SSD', dialCode: '+211', isActive: false },
    { name: 'Suecia', isoCode: 'SWE', dialCode: '+46', isActive: true },
    { name: 'Suiza', isoCode: 'CHE', dialCode: '+41', isActive: true },
    { name: 'Surinam', isoCode: 'SUR', dialCode: '+597', isActive: true },
    { name: 'Svalbard y Jan Mayen', isoCode: 'SJM', dialCode: '+47', isActive: false },
    { name: 'Tailandia', isoCode: 'THA', dialCode: '+66', isActive: false },
    { name: 'Taiwán', isoCode: 'TWN', dialCode: '+886', isActive: false },
    { name: 'Tanzania', isoCode: 'TZA', dialCode: '+255', isActive: false },
    { name: 'Tayikistán', isoCode: 'TJK', dialCode: '+992', isActive: false },
    { name: 'Territorio Británico del Océano Índico', isoCode: 'IOT', dialCode: '+246', isActive: false },
    { name: 'Tierras Australes y Antárticas Francesas', isoCode: 'ATF', dialCode: '+262', isActive: false },
    { name: 'Timor Oriental', isoCode: 'TLS', dialCode: '+670', isActive: false },
    { name: 'Togo', isoCode: 'TGO', dialCode: '+228', isActive: false },
    { name: 'Tokelau', isoCode: 'TKL', dialCode: '+690', isActive: false },
    { name: 'Tonga', isoCode: 'TON', dialCode: '+676', isActive: false },
    { name: 'Trinidad y Tobago', isoCode: 'TTO', dialCode: '+1-868', isActive: true },
    { name: 'Túnez', isoCode: 'TUN', dialCode: '+216', isActive: false },
    { name: 'Turkmenistán', isoCode: 'TKM', dialCode: '+993', isActive: false },
    { name: 'Turquía', isoCode: 'TUR', dialCode: '+90', isActive: true },
    { name: 'Tuvalu', isoCode: 'TUV', dialCode: '+688', isActive: false },
    { name: 'Ucrania', isoCode: 'UKR', dialCode: '+380', isActive: true },
    { name: 'Uganda', isoCode: 'UGA', dialCode: '+256', isActive: false },
    { name: 'Uruguay', isoCode: 'URY', dialCode: '+598', isActive: true },
    { name: 'Uzbekistán', isoCode: 'UZB', dialCode: '+998', isActive: false },
    { name: 'Vanuatu', isoCode: 'VUT', dialCode: '+678', isActive: false },
    { name: 'Vaticano', isoCode: 'VAT', dialCode: '+379', isActive: true },
    { name: 'Venezuela', isoCode: 'VEN', dialCode: '+58', isActive: true },
    { name: 'Vietnam', isoCode: 'VNM', dialCode: '+84', isActive: false },
    { name: 'Wallis y Futuna', isoCode: 'WLF', dialCode: '+681', isActive: false },
    { name: 'Yemen', isoCode: 'YEM', dialCode: '+967', isActive: false },
    { name: 'Yibuti', isoCode: 'DJI', dialCode: '+253', isActive: false },
    { name: 'Zambia', isoCode: 'ZMB', dialCode: '+260', isActive: false },
    { name: 'Zimbabue', isoCode: 'ZWE', dialCode: '+263', isActive: false },
  ];

  try {
    for (const country of countriesData) {
      await masterDb
        .insert(countries)
        .values(country)
        .onConflictDoUpdate({
          target: countries.isoCode,
          set: { isActive: country.isActive },
        });
    }
    console.log('✅ Países insertados correctamente en el Master.');
  } catch (error) {
    console.error('❌ Error al insertar países:', error);
  } finally {
    process.exit(0);
  }
}

seedCountries();