import { db } from '../db';
import { currencies } from '../db/master/schema';

const allCurrencies = [
  { name: 'Dírham Emiratense', isoCode: 'AED', symbol: 'د.إ', isActive: false },
  { name: 'Afgani Afgano', isoCode: 'AFN', symbol: '؋', isActive: false },
  { name: 'Lek Albanés', isoCode: 'ALL', symbol: 'L', isActive: true },
  { name: 'Dram Armenio', isoCode: 'AMD', symbol: '֏', isActive: true },
  { name: 'Florín Antillano', isoCode: 'ANG', symbol: 'ƒ', isActive: true },
  { name: 'Kwanza Angoleño', isoCode: 'AOA', symbol: 'Kz', isActive: false },
  { name: 'Peso Argentino', isoCode: 'ARS', symbol: '$', isActive: true },
  { name: 'Dólar Australiano', isoCode: 'AUD', symbol: 'A$', isActive: false },
  { name: 'Florín Arubeño', isoCode: 'AWG', symbol: 'ƒ', isActive: true },
  { name: 'Manat Azerbaiyano', isoCode: 'AZN', symbol: '₼', isActive: true },
  { name: 'Marco Convertible Bosnio', isoCode: 'BAM', symbol: 'KM', isActive: true },
  { name: 'Dólar Barbadense', isoCode: 'BBD', symbol: 'Bds$', isActive: true },
  { name: 'Taka Bangladesí', isoCode: 'BDT', symbol: '৳', isActive: false },
  { name: 'Lev Búlgaro', isoCode: 'BGN', symbol: 'лв', isActive: true },
  { name: 'Dinar Bareiní', isoCode: 'BHD', symbol: '.د.ب', isActive: false },
  { name: 'Franco Burundiano', isoCode: 'BIF', symbol: 'Fr', isActive: false },
  { name: 'Dólar Bermudeño', isoCode: 'BMD', symbol: 'BD$', isActive: true },
  { name: 'Dólar Bruneano', isoCode: 'BND', symbol: 'B$', isActive: false },
  { name: 'Boliviano', isoCode: 'BOB', symbol: 'Bs', isActive: true },
  { name: 'Real Brasileño', isoCode: 'BRL', symbol: 'R$', isActive: true },
  { name: 'Dólar Bahameño', isoCode: 'BSD', symbol: 'B$', isActive: true },
  { name: 'Ngultrum Butanés', isoCode: 'BTN', symbol: 'Nu.', isActive: false },
  { name: 'Pula Botsuano', isoCode: 'BWP', symbol: 'P', isActive: false },
  { name: 'Rublo Bielorruso', isoCode: 'BYN', symbol: 'Br', isActive: true },
  { name: 'Dólar Beliceño', isoCode: 'BZD', symbol: 'BZ$', isActive: true },
  { name: 'Dólar Canadiense', isoCode: 'CAD', symbol: 'CA$', isActive: true },
  { name: 'Franco Congoleño', isoCode: 'CDF', symbol: 'FC', isActive: false },
  { name: 'Franco Suizo', isoCode: 'CHF', symbol: 'CHF', isActive: true },
  { name: 'Peso Chileno', isoCode: 'CLP', symbol: '$', isActive: true },
  { name: 'Yuan Chino', isoCode: 'CNY', symbol: '¥', isActive: false },
  { name: 'Peso Colombiano', isoCode: 'COP', symbol: '$', isActive: true },
  { name: 'Colón Costarricense', isoCode: 'CRC', symbol: '₡', isActive: true },
  { name: 'Peso Cubano Convertible', isoCode: 'CUC', symbol: 'CUC$', isActive: false },
  { name: 'Peso Cubano', isoCode: 'CUP', symbol: '₱', isActive: true },
  { name: 'Escudo Caboverdiano', isoCode: 'CVE', symbol: '$', isActive: false },
  { name: 'Corona Checa', isoCode: 'CZK', symbol: 'Kč', isActive: true },
  { name: 'Franco Yibutiano', isoCode: 'DJF', symbol: 'Fdj', isActive: false },
  { name: 'Corona Danesa', isoCode: 'DKK', symbol: 'kr', isActive: true },
  { name: 'Peso Dominicano', isoCode: 'DOP', symbol: 'RD$', isActive: true },
  { name: 'Dinar Argelino', isoCode: 'DZD', symbol: 'د.ج', isActive: false },
  { name: 'Libra Egipcia', isoCode: 'EGP', symbol: '£', isActive: false },
  { name: 'Nakfa Eritreo', isoCode: 'ERN', symbol: 'Nfk', isActive: false },
  { name: 'Birr Etíope', isoCode: 'ETB', symbol: 'Br', isActive: false },
  { name: 'Euro', isoCode: 'EUR', symbol: '€', isActive: true },
  { name: 'Dólar Fiyiano', isoCode: 'FJD', symbol: 'FJ$', isActive: false },
  { name: 'Libra Malvinense', isoCode: 'FKP', symbol: '£', isActive: true },
  { name: 'Libra Esterlina', isoCode: 'GBP', symbol: '£', isActive: true },
  { name: 'Lari Georgiano', isoCode: 'GEL', symbol: '₾', isActive: true },
  { name: 'Cedi Ghanés', isoCode: 'GHS', symbol: '₵', isActive: false },
  { name: 'Libra Gibraltareña', isoCode: 'GIP', symbol: '£', isActive: true },
  { name: 'Dalasi Gambiano', isoCode: 'GMD', symbol: 'D', isActive: false },
  { name: 'Franco Guineano', isoCode: 'GNF', symbol: 'FG', isActive: false },
  { name: 'Quetzal Guatemalteco', isoCode: 'GTQ', symbol: 'Q', isActive: true },
  { name: 'Dólar Guyanés', isoCode: 'GYD', symbol: 'G$', isActive: true },
  { name: 'Dólar de Hong Kong', isoCode: 'HKD', symbol: 'HK$', isActive: false },
  { name: 'Lempira Hondureño', isoCode: 'HNL', symbol: 'L', isActive: true },
  { name: 'Kuna Croata', isoCode: 'HRK', symbol: 'kn', isActive: false },
  { name: 'Gourde Haitiano', isoCode: 'HTG', symbol: 'G', isActive: true },
  { name: 'Forinto Húngaro', isoCode: 'HUF', symbol: 'Ft', isActive: true },
  { name: 'Rupia Indonesia', isoCode: 'IDR', symbol: 'Rp', isActive: false },
  { name: 'Nuevo Shekel Israelí', isoCode: 'ILS', symbol: '₪', isActive: false },
  { name: 'Rupia India', isoCode: 'INR', symbol: '₹', isActive: false },
  { name: 'Dinar Iraquí', isoCode: 'IQD', symbol: 'ع.د', isActive: false },
  { name: 'Rial Iraní', isoCode: 'IRR', symbol: '﷼', isActive: false },
  { name: 'Corona Islandesa', isoCode: 'ISK', symbol: 'kr', isActive: true },
  { name: 'Dólar Jamaiquino', isoCode: 'JMD', symbol: 'J$', isActive: true },
  { name: 'Dinar Jordano', isoCode: 'JOD', symbol: 'د.ا', isActive: false },
  { name: 'Yen Japonés', isoCode: 'JPY', symbol: '¥', isActive: false },
  { name: 'Chelín Keniata', isoCode: 'KES', symbol: 'KSh', isActive: false },
  { name: 'Som Kirguís', isoCode: 'KGS', symbol: 'с', isActive: false },
  { name: 'Riel Camboyano', isoCode: 'KHR', symbol: '៛', isActive: false },
  { name: 'Franco Comorense', isoCode: 'KMF', symbol: 'CF', isActive: false },
  { name: 'Won Norcoreano', isoCode: 'KPW', symbol: '₩', isActive: false },
  { name: 'Won Surcoreano', isoCode: 'KRW', symbol: '₩', isActive: false },
  { name: 'Dinar Kuwaití', isoCode: 'KWD', symbol: 'د.ك', isActive: false },
  { name: 'Dólar de las Islas Caimán', isoCode: 'KYD', symbol: 'CI$', isActive: true },
  { name: 'Kip Lao', isoCode: 'LAK', symbol: '₭', isActive: false },
  { name: 'Libra Libanesa', isoCode: 'LBP', symbol: 'ل.ل', isActive: false },
  { name: 'Dólar Liberiano', isoCode: 'LRD', symbol: 'L$', isActive: false },
  { name: 'Loti Lesotense', isoCode: 'LSL', symbol: 'L', isActive: false },
  { name: 'Dinar Libio', isoCode: 'LYD', symbol: 'ل.د', isActive: false },
  { name: 'Dirham Marroquí', isoCode: 'MAD', symbol: 'د.م.', isActive: false },
  { name: 'Leu Moldavo', isoCode: 'MDL', symbol: 'L', isActive: true },
  { name: 'Ariary Malgache', isoCode: 'MGA', symbol: 'Ar', isActive: false },
  { name: 'Denar Macedonio', isoCode: 'MKD', symbol: 'ден', isActive: true },
  { name: 'Kyat Birmano', isoCode: 'MMK', symbol: 'K', isActive: false },
  { name: 'Tugrik Mongol', isoCode: 'MNT', symbol: '₮', isActive: false },
  { name: 'Pataca Macaense', isoCode: 'MOP', symbol: 'MOP$', isActive: false },
  { name: 'Ouguiya Mauritano', isoCode: 'MRU', symbol: 'UM', isActive: false },
  { name: 'Rupia de Mauricio', isoCode: 'MUR', symbol: 'Rs', isActive: false },
  { name: 'Rupia Maldiva', isoCode: 'MVR', symbol: 'Rf', isActive: false },
  { name: 'Kwacha Malauí', isoCode: 'MWK', symbol: 'MK', isActive: false },
  { name: 'Peso Mexicano', isoCode: 'MXN', symbol: '$', isActive: true },
  { name: 'Ringgit Malayo', isoCode: 'MYR', symbol: 'RM', isActive: false },
  { name: 'Metical Mozambiqueño', isoCode: 'MZN', symbol: 'MT', isActive: false },
  { name: 'Dólar Namibio', isoCode: 'NAD', symbol: 'N$', isActive: false },
  { name: 'Naira Nigeriana', isoCode: 'NGN', symbol: '₦', isActive: false },
  { name: 'Córdoba Nicaragüense', isoCode: 'NIO', symbol: 'C$', isActive: true },
  { name: 'Corona Noruega', isoCode: 'NOK', symbol: 'kr', isActive: true },
  { name: 'Rupia Nepalí', isoCode: 'NPR', symbol: 'Rs', isActive: false },
  { name: 'Dólar Neozelandés', isoCode: 'NZD', symbol: 'NZ$', isActive: false },
  { name: 'Rial Omaní', isoCode: 'OMR', symbol: 'ر.ع.', isActive: false },
  { name: 'Balboa Panameño', isoCode: 'PAB', symbol: 'B/.', isActive: true },
  { name: 'Sol Peruano', isoCode: 'PEN', symbol: 'S/', isActive: true },
  { name: 'Kina Papuano', isoCode: 'PGK', symbol: 'K', isActive: false },
  { name: 'Peso Filipino', isoCode: 'PHP', symbol: '₱', isActive: false },
  { name: 'Rupia Pakistaní', isoCode: 'PKR', symbol: 'Rs', isActive: false },
  { name: 'Zloty Polaco', isoCode: 'PLN', symbol: 'zł', isActive: true },
  { name: 'Guaraní Paraguayo', isoCode: 'PYG', symbol: '₲', isActive: true },
  { name: 'Riyal Catarí', isoCode: 'QAR', symbol: 'ر.ق', isActive: false },
  { name: 'Leu Rumano', isoCode: 'RON', symbol: 'lei', isActive: true },
  { name: 'Dinar Serbio', isoCode: 'RSD', symbol: 'din.', isActive: true },
  { name: 'Rublo Ruso', isoCode: 'RUB', symbol: '₽', isActive: true },
  { name: 'Franco Ruandés', isoCode: 'RWF', symbol: 'FRw', isActive: false },
  { name: 'Riyal Saudí', isoCode: 'SAR', symbol: 'ر.س', isActive: false },
  { name: 'Dólar de las Islas Salomón', isoCode: 'SBD', symbol: 'SI$', isActive: false },
  { name: 'Rupia Seychellense', isoCode: 'SCR', symbol: 'Rs', isActive: false },
  { name: 'Libra Sudanesa', isoCode: 'SDG', symbol: 'ج.س.', isActive: false },
  { name: 'Corona Sueca', isoCode: 'SEK', symbol: 'kr', isActive: true },
  { name: 'Dólar Singapurense', isoCode: 'SGD', symbol: 'S$', isActive: false },
  { name: 'Libra de Santa Elena', isoCode: 'SHP', symbol: '£', isActive: false },
  { name: 'Leone Sierra Leonés', isoCode: 'SLE', symbol: 'Le', isActive: false },
  { name: 'Chelín Somalí', isoCode: 'SOS', symbol: 'S', isActive: false },
  { name: 'Dólar Surinamés', isoCode: 'SRD', symbol: '$', isActive: true },
  { name: 'Libra Sursudanesa', isoCode: 'SSP', symbol: '£', isActive: false },
  { name: 'Dobra de Santo Tomé y Príncipe', isoCode: 'STN', symbol: 'Db', isActive: false },
  { name: 'Colón Salvadoreño', isoCode: 'SVC', symbol: '₡', isActive: false },
  { name: 'Libra Siria', isoCode: 'SYP', symbol: '£S', isActive: false },
  { name: 'Lilangeni Suazi', isoCode: 'SZL', symbol: 'E', isActive: false },
  { name: 'Baht Tailandés', isoCode: 'THB', symbol: '฿', isActive: false },
  { name: 'Somoni Tayiko', isoCode: 'TJS', symbol: 'SM', isActive: false },
  { name: 'Manat Turcomano', isoCode: 'TMT', symbol: 'm', isActive: false },
  { name: 'Dinar Tunecino', isoCode: 'TND', symbol: 'د.ت', isActive: false },
  { name: 'Pa\'anga Tongano', isoCode: 'TOP', symbol: 'T$', isActive: false },
  { name: 'Lira Turca', isoCode: 'TRY', symbol: '₺', isActive: true },
  { name: 'Dólar Trinitense', isoCode: 'TTD', symbol: 'TT$', isActive: true },
  { name: 'Dólar Taiwanés', isoCode: 'TWD', symbol: 'NT$', isActive: false },
  { name: 'Chelín Tanzano', isoCode: 'TZS', symbol: 'TSh', isActive: false },
  { name: 'Grivna Ucraniana', isoCode: 'UAH', symbol: '₴', isActive: true },
  { name: 'Chelín Ugandés', isoCode: 'UGX', symbol: 'USh', isActive: false },
  { name: 'Dólar Estadounidense', isoCode: 'USD', symbol: '$', isActive: true },
  { name: 'Peso Uruguayo', isoCode: 'UYU', symbol: '$U', isActive: true },
  { name: 'Som Uzbeko', isoCode: 'UZS', symbol: 'so\'m', isActive: false },
  { name: 'Bolívar Soberano Venezolano', isoCode: 'VES', symbol: 'Bs.S', isActive: true },
  { name: 'Dong Vietnamita', isoCode: 'VND', symbol: '₫', isActive: false },
  { name: 'Vatu Vanuatense', isoCode: 'VUV', symbol: 'VT', isActive: false },
  { name: 'Tālā Samoano', isoCode: 'WST', symbol: 'T', isActive: false },
  { name: 'Franco CFA de África Central', isoCode: 'XAF', symbol: 'FCFA', isActive: false },
  { name: 'Dólar del Caribe Oriental', isoCode: 'XCD', symbol: '$', isActive: true },
  { name: 'Franco CFA de África Occidental', isoCode: 'XOF', symbol: 'CFA', isActive: false },
  { name: 'Franco CFP', isoCode: 'XPF', symbol: 'Fr', isActive: false },
  { name: 'Rial Yemení', isoCode: 'YER', symbol: '﷼', isActive: false },
  { name: 'Rand Sudafricano', isoCode: 'ZAR', symbol: 'R', isActive: false },
  { name: 'Kwacha Zambiano', isoCode: 'ZMW', symbol: 'ZK', isActive: false },
  { name: 'Dólar Zimbabwe Gold', isoCode: 'ZWG', symbol: 'ZiG', isActive: false },
  { name: 'Dólar Zimbabuense', isoCode: 'ZWL', symbol: 'Z$', isActive: false },
];

async function seedCurrencies() {
  console.log('🌱 Iniciando seed de monedas...');
  try {
    for (const currency of allCurrencies) {
      try {
        await db
          .insert(currencies)
          .values(currency)
          .onConflictDoUpdate({
            target: currencies.isoCode,
            set: { isActive: currency.isActive },
          });
      } catch (err) {
        console.error(`Error inserting ${currency.name}:`, err);
      }
    }
    console.log('✅ Monedas insertadas correctamente.');
  } catch (error) {
    console.error('❌ Error al insertar monedas:', error);
  } finally {
    process.exit(0);
  }
}

seedCurrencies();
